<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>AnyStateClaimsPortal.Web</AssemblyName>
    <OutputType>Exe</OutputType>
    <RootNamespace>AnyStateClaimsPortal.Web</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Global.asax.cs"></Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CoreWCF.Primitives" Version="0.1.0"></PackageReference>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.7"></PackageReference>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0"></PackageReference>
    <PackageReference Include="EntityFramework" Version="6.5.1"></PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4"></PackageReference>
  </ItemGroup>
</Project>