<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AnyStateClaimsPortal.Tests</AssemblyName>
    <OutputType>Library</OutputType>
    <RootNamespace>AnyStateClaimsPortal.Tests</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit3TestAdapter" Version="[3.0.10, 6.2.0]"></PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="[15.0.0, 18.5.1]"></PackageReference>
    <PackageReference Include="NUnit" Version="*"></PackageReference>
    <PackageReference Include="EntityFramework" Version="6.5.1"></PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4"></PackageReference>
    <PackageReference Include="CoreWCF.Primitives" Version="0.1.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AnyStateClaimsPortal.Web\AnyStateClaimsPortal.Web.csproj">
      <Name>AnyStateClaimsPortal.Web</Name>
    </ProjectReference>
  </ItemGroup>
</Project>